### ISSUE TITLE
Ensure it's safe to reload

### ISSUE THREAD

**Issue by Manason** [Qbox-project/qbx_prison#14]
### The problem

qbx_prison shouldn't reasonably break any features when reloading the resource. An example of a feature that's reasonable to break would be losing progress on electrical box job.

### Ideal solution

Test if this is the case already, and if not, use the resource load/unload event handlers to fix the issue.

**Comment by BerkieBb** [comment]
> use the resource load/unload event handlers to fix the issue.

That would mean either saving to kvp or using the database.

If using kvp btw, use the server side because the way client saving works doesn't make sense to use here

**Comment by Manason** [comment]
> > use the resource load/unload event handlers to fix the issue.
> 
> That would mean either saving to kvp or using the database.
> 
> If using kvp btw, use the server side because the way client saving works doesn't make sense to use here

The value that matters, time-left, is already persisted to the db I believe as it's saved on the core's player object. However, other things don't matter that much. So while kvp would be a nice addition, I think the bare minimum for this is to not have errors in console. I already did the onResourceLoad side of this, but I'm not really cleaning up things, so I suspect we just need to remove the ox_lib zones onResourceStop to satisfy the requirement.
